steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/$_AR_NAME:15.0
      - -t
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/$_AR_NAME:$COMMIT_SHA
      - .
      - -f
      - Dockerfile
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_AR_HOSTNAME/$PROJECT_ID/$_AR_NAME
      - --all-tags
    id: Push
