services:

  odoo17-database:
    image: postgres:15
    container_name: odoo17-database
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - odoo17-database-data:$PGDATA

  odoo17-erp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: odoo17-erp
    ports:
      - "80:8080"
    env_file:
      - .env
    tty: true
    depends_on:
      - odoo17-database
    links:
      - odoo17-database
    volumes:
      - odoo17-erp-data:/mnt
    platform: linux/amd64

volumes:
  odoo17-database-data:
    driver: local
  odoo17-erp-data: {}
