services:

  odoo14-ce-db:
    image: postgres:15
    container_name: odoo14-ce-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - odoo14-ce-db-data:$PGDATA

  odoo14-ce-erp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: odoo14-ce-erp
    env_file:
      - .env
    tty: true
    depends_on:
      - odoo14-ce-db
    volumes:
      - odoo14-ce-erp-data:/var/lib/odoo
    platform: linux/amd64

  odoo14-ce-web:
    image: nginx
    container_name: odoo14-ce-web
    ports:
      - "80:8080"
    depends_on:
      - odoo14-ce-erp
    volumes:
      - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  odoo14-ce-db-data:
    driver: local
  odoo14-ce-erp-data: {}
