services:

  odoo17-ce-db:
    image: postgres:15
    container_name: odoo17-ce-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - odoo17-ce-db-data:$PGDATA

  odoo17-ce-erp:
    image: asia.gcr.io/dakonerp-com/odoo/17-ce:slim-alpha
    container_name: odoo17-ce-erp
    env_file:
      - .env
    tty: true
    depends_on:
      - odoo17-ce-db
    volumes:
      - odoo17-ce-erp-data:/var/lib/odoo
    platform: linux/amd64

  odoo17-ce-web:
    image: nginx
    container_name: odoo17-ce-web
    ports:
      - "80:8080"
    depends_on:
      - odoo17-ce-erp
    volumes:
      - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  odoo17-ce-db-data:
    driver: local
  odoo17-ce-erp-data: {}
