version: '3.2'
services:

  odoo-database:
    image: postgres:15
    container_name: odoo-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-database-data:/var/lib/postgresql/data/pgdata

  odoo-erp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: odoo-erp
    ports:
      - "80:8080"
    environment:
      - OPTIONS__ADMIN_PASSWD=secret
      - OPTIONS__ADDONS_PATH=/mnt/addons/community,/mnt/addons/enterprise
      - OPTIONS__DATA_DIR=/mnt/odoo-data
      - OPTIONS__LOG_HANDLER=:INFO
      - OPTIONS__LOG_LEVEL=info
      - OPTIONS__DB_HOST=odoo-database
      - OPTIONS__DB_PORT=5432
      - OPTIONS__DB_USER=odoo
      - OPTIONS__DB_NAME=False
      - OPTIONS__DB_PASSWORD=odoo
      - OPTIONS__WORKERS=3
    tty: true
    depends_on:
      - odoo-database
    links:
      - odoo-database
    volumes:
      - ./addons:/mnt/efishery_addons
      - odoo-erp-data:/mnt
    platform: linux/amd64

volumes:
  odoo-database-data:
    driver: local
  odoo-erp-data: {}
